<a href="https://colab.research.google.com/github/heythisbenittababu/Assessment2_numpypandas_BenittaBabu/blob/main/Assessment_numpy%26pandas_benittababu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import numpy as np

Q:1

In [5]:
array=np.array([10, 20, 30, 40, 50])
print("the shape of the array:",array.shape)
print("the datatype of the array:",array.dtype)

the shape of the array: (5,)
the datatype of the array: int64

Q:2

In [60]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print("The sum of an array:", np.sum(arr+5))
print("The multiplication of the array:", np.prod(arr*2))

The sum of an array: 100
The multiplication of the array: 12000000

Q:3

In [18]:
arr = np.array([12, 15, 18, 20, 25, 30])
print("The mean of the array", np.mean(arr))
print("The median of the array", np.median(arr))
print("The standard deviation of the array", np.std(arr))
print("The maximum of the array", np.max(arr))
print("The minimum of the array", np.min(arr))

The mean of the array 20.0
The median of the array 19.0
The standard deviation of the array 6.027713773341708
The maximum of the array 30
The minimum of the array 12

Q:4

In [21]:
arr = np.array([10, 25, 30, 45, 50, 65, 70])
filtered = arr[arr > 40]
print(filtered)

[45 50 65 70]

In [22]:
import pandas as pd

Q:5

In [24]:
df=pd.DataFrame({'Name':['Anu','Rahul','Meera','Arun'],'Age':[21,22,20,23],'Score':[85,72,91,68]})
df

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

Q:6

In [35]:
print(df[['Name','Score']])
print(df[df['Name'] == 'Meera'])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68
    Name  Age  Score
2  Meera   20     91

Q:7

In [37]:
df[df['Score'] > 75]

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

Q:8

In [76]:
print("The number of rows and columns:", df.size)
print('\n')
print("columns name:",df.columns)
print('\n')
print("The datatype of the dataframe:",df.dtypes)
print('\n')
print("The statistical summary of the dataframe:",df.describe())

The number of rows and columns: 880


columns name: Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')


The datatype of the dataframe: Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object


The statistical summary of the dataframe:              Age  Attendance  Python_Score   SQL_Score  Pandas_Score  \
count  77.000000   77.000000     78.000000   80.000000     78.000000
mean   22.012987   81.672727     72.821795   70.445000     70.365385
std     2.155126   10.054204     16.722103   14.630417     15.814294
min    19.000000   56.300000     39.500000   38.300000     25.000000
25%    20.000000   75.500000     64.525000   60.650000     61.800000
50%    22.000000   81.100000     72.000000   69.300000     70.000000
75%    24.000000   86.400000     86.525000   81.150000     82.575000
max    25.000000  100.000000    100.000000  100.000000    100.000000

       NumPy_Score  Final_Score
count    78.000000    78.000000
mean     68.574359    70.696154
std      16.417242    14.053871
min      25.000000    40.600000
25%      57.175000    60.450000
50%      70.700000    70.950000
75%      80.650000    82.275000
max     100.000000    97.000000

Q:9

In [50]:
df.sort_values(by='Score', ascending=False)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

Q:10

In [63]:
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})
print(df.isnull())
print('\n')
print(df)
print('\n')
print(df.fillna(np.mean(df['Age'])))
print('\n')
print(df.fillna(np.mean(df['Score'])))

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False


  Name   Age  Score
0    A  21.0   80.0
1    B   NaN   75.0
2    C  23.0    NaN
3    D  22.0   90.0


  Name   Age  Score
0    A  21.0   80.0
1    B  22.0   75.0
2    C  23.0   22.0
3    D  22.0   90.0


  Name        Age      Score
0    A  21.000000  80.000000
1    B  81.666667  75.000000
2    C  23.000000  81.666667
3    D  22.000000  90.000000

Q:11

In [68]:
studentper='/content/sample_data/student_performance.csv'
dfstudent=pd.read_csv(studentper)
dfstudent

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [69]:
dfstudent.head()

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

In [70]:
dfstudent.tail()

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [71]:
df.size

880

In [85]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

In [77]:
df.dtypes

Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

In [79]:
df.describe()

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

Q:12

In [81]:
df[df['Final_Score'] > 75]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7
24,STU1025,Kiran Varma,Female,Electronics,21.0,80.7,87.5,67.1,84.5,96.1,77.3
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1
30,STU1031,Amal Varma,Female,Computer Science,19.0,86.7,86.9,64.3,100.0,89.2,85.5
33,STU1034,Amal Das,Male,Computer Science,19.0,85.5,94.4,81.6,71.3,81.5,84.3
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2
37,STU1038,Kiran Pillai,Female,Electronics,25.0,85.2,87.8,78.3,85.5,82.7,82.4
39,STU1040,Rohan Sharma,Female,Computer Science,21.0,100.0,68.9,79.8,66.1,66.4,78.5
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
41,STU1042,Arun Joseph,Female,Computer Science,21.0,85.9,71.2,76.1,70.8,NaN,77.9
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
51,STU1052,Gokul Nair,Female,Commerce,25.0,77.3,80.4,85.3,96.7,83.5,79.3
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
56,STU1057,Rohan Pillai,Female,Commerce,20.0,79.5,72.1,66.9,61.8,72.3,75.2
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
58,STU1059,Anu Menon,Male,Electronics,24.0,96.7,99.7,77.1,68.9,89.7,84.9
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
73,STU1074,Anu Kumar,Female,Computer Science,22.0,95.0,95.3,67.7,92.4,81.4,83.4
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [83]:
df[df['Attendance'] < 75 ]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
15,STU1016,Nikhil Kumar,Female,Computer Science,NaN,70.3,55.9,69.3,67.1,58.4,58.2
19,STU1020,Vivek Sharma,Female,Commerce,22.0,72.1,65.8,60.9,49.8,44.8,54.6
25,STU1026,Maya Menon,Male,Electronics,20.0,68.3,91.7,64.5,83.5,73.7,69.4
36,STU1037,Nikhil Menon,Male,Electronics,22.0,74.8,69.5,60.7,64.6,81.6,69.1
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
50,STU1051,Gokul Menon,Male,Data Science,25.0,70.9,68.6,81.0,64.0,63.0,70.5
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
71,STU1072,Vivek Pillai,Male,Commerce,24.0,71.5,59.0,58.2,56.3,48.9,56.6

In [86]:
df[(df['Department'] == 'Data Science') & (df['Final_Score'] < 80)]

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
14,STU1015,Diya Pillai,Male,Data Science,19.0,100.0,41.8,47.1,NaN,55.4,47.1
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1
22,STU1023,Rahul Reddy,Female,Data Science,24.0,86.3,73.0,44.8,76.6,51.6,64.6
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1
28,STU1029,Diya Menon,Male,Data Science,19.0,84.3,69.2,64.5,70.0,60.9,62.1
32,STU1033,Fathima Das,Male,Data Science,24.0,83.6,71.7,84.1,52.5,45.2,70.6
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
44,STU1045,Maya Joseph,Male,Data Science,22.0,93.9,56.5,66.9,63.2,61.7,64.6
46,STU1047,Gokul Das,Male,Data Science,21.0,NaN,69.5,59.3,75.2,75.2,74.8
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
50,STU1051,Gokul Menon,Male,Data Science,25.0,70.9,68.6,81.0,64.0,63.0,70.5
65,STU1066,Rohan Thomas,Male,Data Science,25.0,85.3,66.8,57.0,80.6,61.0,61.1
66,STU1067,Rahul Thomas,Male,Data Science,NaN,99.3,NaN,56.2,69.0,81.5,70.7
69,STU1070,Neha Pillai,Male,Data Science,25.0,78.7,40.1,52.1,49.5,52.2,52.1
72,STU1073,Swathi Joseph,Male,Data Science,22.0,78.7,76.4,77.5,73.6,65.6,73.5
74,STU1075,Gokul Nair,Female,Data Science,23.0,87.8,85.4,80.0,65.2,70.4,70.9
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5

In [87]:
df.sort_values(by='Final_Score', ascending=False)

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
...,...,...,...,...,...,...,...,...,...,...,...
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
26,STU1027,Aditya Pillai,Female,Computer Science,25.0,79.6,44.0,52.5,25.0,25.0,40.6
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
53,STU1054,Maya Sharma,Male,Data Science,19.0,82.5,59.7,60.5,65.8,73.3,NaN

Q:13

In [92]:
df['Average_Technical_Score'] = df[['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']].mean(axis=1)
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275
...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075

In [96]:

Result= [0, 60, 75, 90, 101]
labels = ['Needs Improvement', 'Average', 'Good', 'Excellent']
df['Performance'] = pd.cut(df['Final_Score'], bins=bins, labels=labels, right=False)
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

Q:14

In [100]:
df(['Student_id'],index)

NameError: name 'index' is not defined

In [108]:

Average=df['Final_Score'].mean()
print(Average)

np.float64(70.69615384615385)

In [106]:
df['Final_Score'].max()

97.0

In [107]:
df['Final_Score'].min()

40.6

In [110]:
df.sort_values(by='Average', ascending=False)

AttributeError: 'DataFrame' object has no attribute 'sort'

Q:15

In [113]:
scores=df["Final_Score"].dropna().values


print("Mean:", scores.mean())
print("Median:", np.median(scores))
print("Standard Deviation:", scores.std())
print("25th Percentile:", np.percentile(scores, 25))
print("75th Percentile:", np.percentile(scores, 75))

print("Students with Final_Score above the overall mean:")

display(df[df["Final_Score"] > scores.mean()]
)

Mean: 70.69615384615383
Median: 70.95
Standard Deviation: 13.96349124578818
25th Percentile: 60.449999999999996
75th Percentile: 82.275
Students with Final_Score above the overall mean:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0,77.400,Good
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2,74.725,Good
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0,92.125,Good
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8,79.800,Average
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9,95.625,Excellent
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9,81.100,Good
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1,89.350,Excellent
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1,74.825,Good
20,STU1021,Arun Varma,Female,Commerce,25.0,79.5,NaN,67.6,74.3,75.3,73.2,72.400,Average
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7,80.500,Good
24,STU1025,Kiran Varma,Female,Electronics,21.0,80.7,87.5,67.1,84.5,96.1,77.3,83.800,Good
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1,72.375,Good
30,STU1031,Amal Varma,Female,Computer Science,19.0,86.7,86.9,64.3,100.0,89.2,85.5,85.100,Good
33,STU1034,Amal Das,Male,Computer Science,19.0,85.5,94.4,81.6,71.3,81.5,84.3,82.200,Good
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2,87.800,Good
37,STU1038,Kiran Pillai,Female,Electronics,25.0,85.2,87.8,78.3,85.5,82.7,82.4,83.575,Good
39,STU1040,Rohan Sharma,Female,Computer Science,21.0,100.0,68.9,79.8,66.1,66.4,78.5,70.300,Good
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5,87.400,Excellent
41,STU1042,Arun Joseph,Female,Computer Science,21.0,85.9,71.2,76.1,70.8,NaN,77.9,72.700,Good
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3,73.900,Good
46,STU1047,Gokul Das,Male,Data Science,21.0,NaN,69.5,59.3,75.2,75.2,74.8,69.800,Average
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3,74.750,Good
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0,92.800,Excellent
51,STU1052,Gokul Nair,Female,Commerce,25.0,77.3,80.4,85.3,96.7,83.5,79.3,86.475,Good
52,STU1053,Maya Varma,Male,Computer Science,22.0,84.6,71.9,73.4,70.0,67.2,71.0,70.625,Average
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3,86.550,Excellent
56,STU1057,Rohan Pillai,Female,Commerce,20.0,79.5,72.1,66.9,61.8,72.3,75.2,68.275,Good
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3,86.825,Excellent
58,STU1059,Anu Menon,Male,Electronics,24.0,96.7,99.7,77.1,68.9,89.7,84.9,83.850,Good
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9,82.450,Good
60,STU1061,Fathima Sharma,Male,Computer Science,24.0,79.6,80.8,63.1,71.1,67.9,70.8,70.725,Average
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0,95.200,Excellent
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5,83.300,Good
66,STU1067,Rahul Thomas,Male,Data Science,NaN,99.3,NaN,56.2,69.0,81.5,70.7,68.900,Average
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7,83.975,Good
72,STU1073,Swathi Joseph,Male,Data Science,22.0,78.7,76.4,77.5,73.6,65.6,73.5,73.275,Average
73,STU1074,Anu Kumar,Female,Computer Science,22.0,95.0,95.3,67.7,92.4,81.4,83.4,84.200,Good
74,STU1075,Gokul Nair,Female,Data Science,23.0,87.8,85.4,80.0,65.2,70.4,70.9,75.250,Average
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

In [117]:


import pandas as pd
import numpy as np


df = pd.read_csv("/content/sample_data/student_performance.csv")



print("Missing Values:")
print(df.isnull().sum())


numeric_columns = df.select_dtypes(include="number").columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].mean())

print("\nData after handling missing values:")
print(df)


df["Python_Score"] = [95, 70, 88, 55, 92, 78]
df["SQL_Score"] = [90, 75, 85, 60, 94, 72]
df["Pandas_Score"] = [88, 72, 91, 58, 89, 75]
df["NumPy_Score"] = [92, 68, 87, 62, 90, 74]
df["Attendance"] = [95, 70, 85, 60, 92, 78]
df["Department"] = ["Data Science", "Computer Science", "Data Science", "Physics", "Data Science", "Chemistry"]





df["Average_Score"] = df[
    ["Python_Score", "SQL_Score", "Pandas_Score", "NumPy_Score"]
].mean(axis=1)


df["Pass_Status"] = np.where(
    df["Average_Score"] >= 50,
    "Pass",
    "Fail"
)

print("\nData after Feature Engineering:")
print(df)

top_5 = df.sort_values(
    "Average_Score",
    ascending=False
).head(5)

print("\nTop 5 Students:")
print(top_5)



department_scores = df.groupby("Department")["Average_Score"].mean()

print("\nAverage Score by Department:")
print(department_scores)

print("\nDepartment with Highest Average Score:")
print(department_scores.idxmax())


attendance = df.groupby("Department")["Attendance"].mean()

print("\nAverage Attendance by Department:")
print(attendance)



print("\nNumber of Students Passed and Failed:")
print(df["Pass_Status"].value_counts())



summary = df.groupby("Department").agg(
    Total_Students=("Department", "count"),
    Average_Score=("Average_Score", "mean"),
    Average_Attendance=("Attendance", "mean"),
    Pass_Count=("Pass_Status", lambda x: (x == "Pass").sum()),
    Fail_Count=("Pass_Status", lambda x: (x == "Fail").sum())
).reset_index()

print("\nSummary DataFrame:")
print(summary)

Missing Values:
Student_ID      0
Name            0
Gender          0
Department      0
Age             3
Attendance      3
Python_Score    2
SQL_Score       0
Pandas_Score    2
NumPy_Score     2
Final_Score     2
dtype: int64

Data after handling missing values:
   Student_ID            Name  Gender        Department        Age  \
0     STU1001     Rahul Varma    Male  Computer Science  25.000000
1     STU1002    Kiran Pillai    Male  Computer Science  24.000000
2     STU1003  Fathima Joseph  Female       Electronics  21.000000
3     STU1004    Rahul Sharma  Female      Data Science  25.000000
4     STU1005       Asha Nair  Female      Data Science  22.000000
..        ...             ...     ...               ...        ...
75    STU1076     Priya Kumar  Female  Computer Science  24.000000
76    STU1077      Amal Kumar    Male      Data Science  22.012987
77    STU1078  Fathima Sharma    Male  Computer Science  19.000000
78    STU1079    Meera Thomas    Male       Electronics  23.000000
79    STU1080      Diya Varma    Male       Electronics  19.000000

    Attendance  Python_Score  SQL_Score  Pandas_Score  NumPy_Score  \
0         74.7          89.4       86.3          81.9         76.7
1         75.5          70.3       63.1          65.1         62.3
2         60.5          79.9       80.4          65.3         68.0
3         80.4          65.8       50.7          52.6         48.8
4         71.4          90.1       82.9          72.4         87.7
..         ...           ...        ...           ...          ...
75        99.3          46.9       57.6          29.5         57.1
76        93.8          45.8       43.4          58.1         38.8
77        86.4          70.4       75.7          98.2         76.7
78        99.4          64.6       66.5          61.8         52.5
79        86.4          80.5       94.3          58.6         74.9

    Final_Score
0          82.7
1          60.3
2          67.1
3          57.2
4          81.9
..          ...
75         47.2
76         43.5
77         75.2
78         63.4
79         78.6

[80 rows x 11 columns]

ValueError: Length of values (6) does not match length of index (80)